### ISSUE TITLE
(enhancement) - Simple_Player - Add a parameter to avoid  playing in loop

### ISSUE THREAD

**Issue by unspacyar** [yosshin4004/portable_mdx#2]
Hello. I tested the "Simple_Player" and I found it very good.  I only miss an option to disable the "loop mode" (playing endless the same .MDX file).  

With this option, could be useful to play a set of different .MDX file using a bash script.

Thank you for your time :-)

**Comment by yosshin4004** [comment]
I added a new option -maxLoops, -maxDuration, -noFadeout and -noVisualize.
You can disable the loop mode by -maxLoops 1.

I tested following command and I found it works fine.
	`find ./ -name '*.MDX' | xargs -n 1 ./simple_player -maxLoops 1`
It is very useful. Thank for suggestion.

**Comment by unspacyar** [comment]
Hello. I tested the new version and works perfect. Thank you for accept my suggestion.

ありがとうございます
