### ISSUE TITLE
MdxGetTitle failed

### ISSUE THREAD

**Issue by unspacyar** [yosshin4004/portable_mdx#4]
I found a MDX file with the following title: TRIGON    st3&4
If I try to open the MDX file, the application fails with the following message:
"MdxGetTitle failed."

maybe the problem is when trying to parse the '&' character in the title?

I will try to attach the mdx file also.
Thank you!!

**Comment by yosshin4004** [comment]
trigon04.mdx has TAB (char code 0x09) in the mdx title string.
fix MdxGetTitle() to skip it.

Thank you for reporting the problem.

**Comment by unspacyar** [comment]
Hello!  I tested again with the new code and now works perfectly.
Thank you for your help!
